version: '3.3'

services:
  blog:
    image: nginx:latest
    container_name: blog
    restart: "on-failure"
    ports:
      - "80:80"
    volumes:
      - ./blog-cloudserver/client.conf:/etc/nginx/conf.d/client.conf
      - ./blog-cloudserver/server.conf:/etc/nginx/conf.d/server.conf
      - ./blog-client/:/usr/share/nginx/html
      - ./blog-server/app/:/blog-server
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
